---
title: ''
output: html_document
date: "2022-10-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
data<-read.csv("./data.csv")
price<-as.vector(data['Price'])
```

```{r}
glimpse(data)
price<-data[['Price']]
```

```{r}

```

```{r}
colnames(data)[5]<-'Battery'
colnames(data)[6]<-'Screensize'
colnames(data)[10]<-'NumOfProcessor'
colnames(data)[11]<-'Ram'
colnames(data)[12]<-'InternalStorage'
colnames(data)[13]<-'RearCamera'
colnames(data)[14]<-'FrontCamera'
colnames(data)[15]<-'OS'
colnames(data)[16]<-'Wifi'
colnames(data)[19]<-'NumOfSims'
colnames(data)[20]<-'3G'
colnames(data)[21]<-'4G'

colnames(data)
```

```{r}
brand<-data[['Brand']]

```

```{r}
battery<-data[['Battery']]
result<-cor.test(price,battery,method = 'pearson')
print(result)
```

2.2e-16 = 0.00000000000000022

```{r}
screensize<-data[['Screensize']]
result<-cor.test(price,screensize,method = 'pearson')
print(result)

```

```{r}
res_x<-data[['Resolution.x']]
result<-cor.test(price,res_x,method = 'pearson')
print(result)

```

```{r}
res_y<-data[['Resolution.y']]
result<-cor.test(price,res_y,method = 'pearson')
print(result)
```

```{r}
numOfProcessor<-data[['NumOfProcessor']]
result<-cor.test(price,numOfProcessor,method = 'pearson')
print(result)
```
